### ISSUE TITLE
Stacktrace not outputted when running test

### ISSUE THREAD

**Issue by scote** [thymikee/jest-preset-angular#112] opened 2018-01-09 15:34 UTC
In our package.json we have :
- "jest": "^22.0.4"
- "jest-junit": "^3.4.1"
- "jest-preset-angular": "^5.0.0"

When we run our test and an error occurs the stacktrace is not ouputted in console, It's difficult to resolve those tests when we don't know what is the error. 

```
    ENOENT: no such file or directory, open 'C:\test\packages\forms\src\directives\reactive_directives\form_group_directive.ts'
        at Error (native)

      at exports.formatStackTrace (node_modules/jest-message-util/build/index.js:233:20)
      at Array.map (native)
```
Anyone know how to resolve this issue?

**Comment by thymikee** [comment] 2018-01-09 15:42
Looks like this may be caused by this line: https://github.com/facebook/jest/blob/398a238f841ebf6b4535d95d93b89f9c3f673ff9/packages/jest-message-util/src/index.js#L232
Can you debug it locally and see if wrapping the `fs` call with try/catch helps?

**Comment by scote** [comment] 2018-01-09 15:58
Yeah it helps a lot. We can see the error. If we put `console.trace`  inside the catch.

**Comment by thymikee** [comment] 2018-01-09 16:02
Since it's related to Jest, maybe you're interested to send a PR with the fix? 🙂

**Comment by thymikee** [comment] 2018-01-09 16:02
Closing, but let's keep the discussion going

**Comment by blalonde** [comment] 2018-01-09 17:29
Hey, I'm working with scote.
When I output the whole trace by hijacking index.js, we see some file references to \node_modules\ and others to \packages. The thing is, we don't have a packages folder in our solution.

Here's a sample stack (note I replaced some paths with [...])

at FormArray.Object.<anonymous>.FormArray._forEachChild ([...]\node_modules\@angular\forms\bundles\forms.umd.js:3819:23)
    at FormArray.Object.<anonymous>.FormArray._checkAllValuesPresent ([...]\packages\forms\src\model.ts:1603:1)
    at FormArray.Object.<anonymous>.FormArray.setValue ([...]\node_modules\@angular\forms\bundles\forms.umd.js:3704:14)    
at [...]\src\app\users\user-create\user-form\user-form.component.view.spec.ts:83:53

**Comment by thymikee** [comment] 2018-01-09 17:33
Hard to tell anything without a repro. Can you extract the failing code into some repository I can check out?

**Comment by blalonde** [comment] 2018-01-09 18:13
https://github.com/blalonde/jestStackError

**Comment by thymikee** [comment] 2018-01-10 15:07
I'll reopen this, but currently don't have bandwidth to tackle it. Anyone interested in triaging this?

**Comment by scote** [comment] 2018-01-12 14:53
I think this issue could be related to this error : https://github.com/kulshekhar/ts-jest/issues/399

**Comment by AhnpGit** [comment] 2018-01-27 11:11
Hi @scote ,

I see your Jest config in package.json seems to be good. I think the issue might be related to Angular version. I tried to upgrade the example repo to Angular 5.0.0 and the similar error doesn't happen. I don't know if it's possible for you and @blalonde to upgrade to Angular 5.0.0 ?

**Comment by blalonde** [comment] 2018-01-31 15:03
Just upgraded the test solution to angular 5.2.2 and it works.
Luckily for us, we just upgraded to angular 5 in our working project too. 

Thanks for checking this out.

**Closed** 2018-01-31 15:05 UTC
