### ISSUE TITLE
InlineHtmlStripStylesTransformer is not strict enough

### ISSUE THREAD

**Issue by FrozenPandaz** [thymikee/jest-preset-angular#254] opened 2019-04-03 18:17 UTC
## Current Behavior

_Any_ object literals have their property assignments transformed thus causing source code such as:

```ts
console.log({
  styles: ['styles.css']
})
```

to print out

```ts
{
  styles: []
}
```

## Expected Behavior

Only object literals passed to `@angular/core`'s `@Component` decorator should have it's property assignments transformed.

**Comment by FrozenPandaz** [comment] 2019-04-03 18:17
Unless someone else wants to tackle this, I can try and make a PR.

**Comment by ahnpnl** [comment] 2019-04-03 18:18
PR is welcome 👍😀

**Comment by wtho** [comment] 2019-04-03 18:50
Yeah, this caveat is known and discussed
* in the [transformer itself](thymikee/jest-preset-angular/src/InlineHtmlStripStylesTransformer.ts#L11-L14)
* the [original PR]()
* this [follow-up PR](thymikee/jest-preset-angular/pull/211), caused by
* [this issue](https://github.com/thymikee/jest-preset-angular/issues/210).

Problem is, that theoretically someone might rename the annotation, or pull an object into the annotation, that is not declared inside the annotation itself.

The AST transformer does not know if an object is actually *the* Angular Component Decorator or if an object with `styles` and `templateUrl` is actually a component configuration, it only knows in what relation code pieces are and how they are named.

Consider these examples:
```ts
import { Component } from '@angular/core';


// classic and easy
@Component({ templateUrl: './file.html' }) export class MyFirstComp { }

// difficult
const MyAnnotation = Component;
@MyAnnotation({ templateUrl: './file.html' }) export class MySecondComp { }

// also difficult
const componentConfig = { styles: [], templateUrl: './file.html' };
@Component(componentConfig) export class MyThirdComp { }

// also difficult
const partialComponentConfig = { templateUrl: './)
@Component({...partialComponentConfig, styles: []}) export class MyThirdComp { }
```

We should discuss approaches and their caveats before implementing it.

**Comment by electrichead** [comment] 2019-04-03 19:33
Would it be an expectation to even support the second case?
```
const MyAnnotation = Component;
@MyAnnotation({ templateUrl: './file.html' }) export class MySecondComp { }
```

For the others we are guaranteed to be in `@Component`

**Comment by wtho** [comment] 2019-04-03 19:48
I agree, the second example is not very important.

The third and fourth are the problematic ones.

@electrichead The AST transformer is written in TypeScript, but it works with AST objects. AST is a representation of the code text, not of the evaluated objects.

So this situation
```ts
const componentConfig = { styles: [], templateUrl: './file.html' };

@Component(componentConfig) export class MyThirdComp { }
```
is definitely a problem, as in this example each line is an independent object. References are made when JavaScript is interpreted, not when the AST transformer is executed. The `styles` assignment is not inside the decorator and therefore we would have to search for the `componentConfig` variable in the whole file, maybe even in other files if it is imported.

**Comment by FrozenPandaz** [comment] 2019-04-03 21:47
@wtho I see the issues. That is fair.

Let's make it not as strict as looking for where the object literal is.

I think if we check if the file imports Component from `@angular/core` it will be safe enough. The difficult cases are still satisfied since they all have to import from `@angular/core`.

Then we can exclude files which do not include:

```ts
import { Component } from '@angular/core';
import * as core from '@angular/core';
import { Component as Comp } from '@angular/core';
```

What do you think?

**Comment by wtho** [comment] 2019-04-03 22:21
Ok, so one more thought I just had, `templateUrl` is actually more important to be transformed than `styles` to be removed. Without `templateUrl` being transformed to `template`, it will not even load.

`styles` on the other hand is just removed for performance issues (correct me if I'm wrong), as we assume styles are usually not tested in jest, that is better done in e2e frameworks.

### Proposal
We could also think about handling them differently, although this might complicate the code unnecessarily.

**`templateUrl`**:
* replaced everywhere
* alternatively only (as suggested by @FrozenPandaz) in files where `Component` gets imported from `@angular/core` or `TestBed` gets imported from `@angular/core/testing`

**`styles`**:
* replaced only if declared directly inside component decorators

This would seem more practical to me as `styles` is also used in more contexts than `templateUrl`.

**Comment by ahnpnl** [comment] 2019-04-04 04:23
I think the proposal looks practical and good. I vote for it.

**Comment by willyboy** [comment] 2019-04-19 01:03
If someone lands here before that PR is merged - I was able to hack around the problem temporarily by changing:
`mockObj = {
    styles: 'a {color: blue}'
}`
to 
`mockObj = {}
mockObj.styles = 'a {color: blue}'`

**Comment by ali-kamalizade-leanix** [comment] 2019-05-03 13:02
This error was driving me mad until I found this issue.
Glad to see a PR is on the way

**Comment by dirkluijk** [comment] 2019-06-05 14:15
Wow, discovered this today as well. Suddenly a unit test broke after upgrading to Jest 24.

**Comment by wtho** [comment] 2019-06-05 14:23
Yeah, I am almost done with the PR, will submit it next week.

It's not really an error, it is an intrusive caveat that kept the transformer simple, but can create side-effects.

**Comment by dirkluijk** [comment] 2019-06-05 14:24
I renamed my property as an easy workaround. 😉

**Comment by SLKnutson** [comment] 2019-06-10 17:51
This is a nightmare to debug. We were lucky to find it by searching thought node_modules. Is there any that you can do this without using AST Transformations? Or if you are going to use AST Transformations, only modify it when you are sure that it is appropriate?

**Comment by wtho** [comment] 2019-06-18 17:12
@SLKnutson The PR is on the way already #261 

If you want to avoid them, you can remove AST Transformers by overriding the array in your jest config and clearing it. To still use jest without the transformers, you will have to inline your templates and styles though.

Also you can test the branch of the PR with the appropriate implementation on `wtho:feat/ast-transformer-strict-styles` in your project using (in your `package.json`):
`"jest-preset-angular": "github:wtho/jest-preset-angular#feat/ast-transformer-strict-styles"`

Testing and reviewing the implementation can speed up the merge.

Finally you are free to implement and use custom transformers.

**Closed** 2019-06-30 17:46 UTC
