### ISSUE TITLE
[Bug]: Unexpected value 'Module' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation - while Module from library present in transformIgnorePatterns

### ISSUE THREAD

**Issue by polonmedia** [thymikee/jest-preset-angular#2158] opened 2023-07-31 13:33 UTC
### Version

13.1.1

### Steps to reproduce

1. Have angular 12 repository and upgrade to 13.
2. Have angular 13 repository with "uuid": "^9.0.0" in dependencies (for example).
3. Use "uuid" it in .ts file.
4. Configure jest.config as in jest-preset-angular angular ver 13 example (both default and esm).
5. Run jest command.
6. Experience "Jest encountered an unexpected token" error from node_modules. Neither esm or default mode works.

### Expected behavior

There are so much conflicting information around from previous and newer preset versions, I could not find one clear sentence on exactly what to do with these kind of errors. It should either work OOTB or at least have a clear information what to add to where, as ive tried to add transformIgnorePatterns or globals and it does nothing or produces other errors.

### Actual behavior

![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/1af41990-9309-4e94-960e-18fde093fa5d)
 SyntaxError: Unexpected token 'export'

with this config:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/ce581606-b306-429e-9455-18ca4865310b)

As I understand something with modules changed and I should transform or not dist files from node_modules?

### Additional context

There are at least 2 big projects I need to be bumped up regarding angular version and jest, they use variety of dependencies and it is really quite problematic not to know what to do. Ive also tried bumping to ver 15 of angular but that changed nothing, same errors, same behavior. I was careful about using proper dep versions from examples. What should I do? At least a ballpark advice or clear explanation of change in mechanisms would be very welcomed. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.6.1 => 29.6.1
```

**Comment by polonmedia** [comment] 2023-08-03 14:21
I tried this config
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/9e6aa270-0973-4d3a-8cb9-f5d471b9a685)
with this package.json ("@angular/core": "^13.0.0")
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/7431b6d8-be29-4f17-af69-5aa605b01acd)
and still i have this shit
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/38337432-1113-495b-b453-5aad3b0c03d9)
bro wtf, there is no winning, whatever I use in whatever sense - always an issue

**Comment by ahnpnl** [comment] 2023-08-03 14:25
Did you check https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+?

**Comment by polonmedia** [comment] 2023-08-03 14:41
@ahnpnl yes, I did, I started with it, but there are always the same or similiar issues, mainly comming from node_modules

**Comment by ahnpnl** [comment] 2023-08-03 14:45
The error I can see coming from a library you are using `angular-support-bot`, this would mean you need to tell Jest to transform the library files via `transformIgnoredPatterns`

**Comment by polonmedia** [comment] 2023-08-03 14:49
It isnt even clear from the link u sent - should I use the jest.config.ts from here
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/2d7e6d07-901a-4347-8ad9-88b73ba910b2)
or from example?

**Comment by ahnpnl** [comment] 2023-08-03 14:54
> It isnt even clear from the link u sent - should I use the jest.config.ts from here ![image](https://user-images.githubusercontent.com/59230634/258149391-2d7e6d07-901a-4347-8ad9-88b73ba910b2.png) or from example?

This is the part if you want to use ESM mode (The title "Use ES modules" seems to be not clear enough)

In your case, `js` or `ts` config file isn't related. The problem is about Jest can't transform files from your `node_modules` for some reasons. The only way to fix is modifying `transformIgnorePatterns`.

If your project doesn't have any custom config on transforming files, perhaps you can compare your project config with example project https://github.com/thymikee/jest-preset-angular/blob/main/examples/example-app-v13/jest.config.js?

**Comment by polonmedia** [comment] 2023-08-03 15:00
I also noticed that u enable this - skipNgcc: false,
but whenever I dont turn it to true, the following happens:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/a5f97844-8630-4022-a417-10e88c41e7f7)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/c9234122-5e59-4dc4-88ff-d3605dc53218)

can it be somehow related?

**Comment by polonmedia** [comment] 2023-08-03 15:10
If i skip it, following happens:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/6212f238-ab05-4f0f-b313-1bac1f3b6b59)

![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/0f9a57da-6268-46cf-b313-d51f987ca239)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/751030f9-3256-4802-a743-4019c6f13dc3)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/3b3ae060-8d34-4332-9671-89379dc379f9)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/81c11a45-f4de-4afc-ac91-c72eedcb4705)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/6bee2523-8c2a-46aa-99c7-f2bae4c29a2f)

am i mentally challanged? something seems off whatever i try to do

**Comment by ahnpnl** [comment] 2023-08-03 15:16
I'd recommend to keep `skipNgcc: false`, this ensures you are compatible with future Angular versions, in v16 they removed View Engine.

It's hard to check about this without a repo. Maybe you can somehow replicate the issue in the `example-app-v13`?

**Comment by polonmedia** [comment] 2023-08-04 08:53
@ahnpnl brother, i added this to the mjs config 
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/4dd6024c-1aa2-41ec-814e-acdb2de1ecb7)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/47f7f3d4-6a1e-4c06-b6ba-0d81b2a81ab6)

but i get those errors now:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/cce44fe2-b6ea-4511-a927-2083db9e1d28)
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/f66ad6c3-b798-4f6d-9063-968486e038fa)
could u advise me to what direction should i look for?

**Comment by ahnpnl** [comment] 2023-08-04 09:01
I can see that you are running Jest in ESM mode. The 2nd screenshot has a lib called `cytiva-cui-design-ng` and the js of this lib is loaded with `umd`. Maybe you can use `moduleNameMapper` to instruct Jest to load `mjs` file instead?

Moving to ESM mode is a very big thing btw. Normally I make CJS mode work first before trying out ESM mode.

**Comment by polonmedia** [comment] 2023-08-10 10:32
@ahnpnl thank u for your patience and responding to me, I managed to get past the config with your guidance and tests are almost working, I have one issue left to which I cannot comprehend and to which I cannot find a clear answer

I get this error while trying to use modules from my components library 
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/2e6979bf-605c-4abf-b021-1816676cd069)

This is how my library is in dist folder:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/2e22105b-3f9c-4466-a429-7601e13f4862)

(I think it may be related) As I mentioned before, I have issue with running ngcc which produces following error
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/dc3d1fe9-37f3-4271-986c-9167fb0763c0)

Could you perhaps point me to direction I should take to resolve this?

**Comment by polonmedia** [comment] 2023-08-11 13:27
I managed to tell ngcc to ignore the lib via this config:
![image](https://github.com/thymikee/jest-preset-angular/assets/59230634/4a58162c-f8d7-440b-aa31-f4412ad6a2a7)
But didnt resolve my issue

**Comment by polonmedia** [comment] 2023-08-11 13:46
Bumping to angular ver 14 didnt resolve nothing also

**Comment by ahnpnl** [comment] 2024-05-10 03:22
I'm sorry I was busy. Now coming back to this I lost the context of what we've tried

**Closed** 2024-06-22 11:19 UTC
Labels: :man_shrugging: Needs More Info, Needs Repo
