### ISSUE TITLE
DI error with v9.0.0-next.1

### ISSUE THREAD

**Issue by canserkanuren** [thymikee/jest-preset-angular#594] opened 2020-11-02 09:20 UTC
## 🐛 Bug Report

I have been trying to implement a library in Angular, and add Jest in this project.
Configuration seems to be fine, but when I installed `@angular/material` package, and add some Material imports into my main library module, the unit tests fail and throws this error :
```
$ npm run test:lib

> my-lib-with-jest@0.0.0 test:lib /Users/canserkanuren/workspace/angular-material-lib/my-lib-with-jest
> jest --config ./projects/my-lib/jest.config.js

 FAIL  projects/my-lib/src/lib/my-lib.service.spec.ts
  MyLibService
    ✕ should be created (246 ms)

  ● MyLibService › should be created

    TypeError: Cannot read property 'ɵprov' of undefined

      at getInjectableDef (../../../packages/core/src/di/interface/defs.ts:198:37)
      at resolveNgModuleDep (../../../packages/core/src/view/ng_module.ts:113:26)
      at NgModuleRef_.Object.<anonymous>.NgModuleRef_.get (../../../packages/core/src/view/refs.ts:420:12)
      at injectInjectorOnly (../../../packages/core/src/di/injector_compatibility.ts:111:29)
      at ɵɵinject (../../../packages/core/src/di/injector_compatibility.ts:131:54)
      at injectArgs (../../../packages/core/src/di/injector_compatibility.ts:232:17)
      at ../../../packages/core/src/di/util.ts:55:30
      at _callFactory (../../../packages/core/src/view/ng_module.ts:200:14)
      at _createProviderInstance (../../../packages/core/src/view/ng_module.ts:153:20)
      at resolveNgModuleDep (../../../packages/core/src/view/ng_module.ts:125:15)
      at NgModuleRef_.Object.<anonymous>.NgModuleRef_.get (../../../packages/core/src/view/refs.ts:420:12)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.inject (../../../packages/core/testing/src/test_bed.ts:487:45)
      at Function.Object.<anonymous>.TestBedViewEngine.inject (../../../packages/core/testing/src/test_bed.ts:227:36)
      at src/lib/my-lib.service.spec.ts:19:23

  ● MyLibService › should be created

    expect(received).toBeTruthy()

    Received: undefined

      21 | 
      22 |   it('should be created', () => {
    > 23 |     expect(service).toBeTruthy();
         |                     ^
      24 |   });
      25 | });
      26 | 

      at src/lib/my-lib.service.spec.ts:23:21

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.881 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-lib-with-jest@0.0.0 test:lib: `jest --config ./projects/my-lib/jest.config.js`
npm ERR! Exit status 1
```

Meanwhile, I did this in a new Angular project, without Jest but with karma, and this error doesn't seem to appear.
I read last night that you have been trying to adapt this library with `ngcc`. So I thought : "Hey, why don't I use the experimental version of this library, e.g. `9.0.0.next-1`".
But no luck, I'm having this error right now :
```
> my-lib-with-jest@0.0.0 test:lib /Users/canserkanuren/workspace/angular-material-lib/my-lib-with-jest
> jest --config ./projects/my-lib/jest.config.js

 FAIL  projects/my-lib/src/lib/my-lib.service.spec.ts
  MyLibService
    ✕ should be created (36 ms)

  ● MyLibService › should be created

    TypeError: Cannot read property 'getComponentFromError' of null

      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (../../../packages/core/testing/src/test_bed.ts:391:46)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.inject (../../../packages/core/testing/src/test_bed.ts:480:10)
      at Function.Object.<anonymous>.TestBedViewEngine.inject (../../../packages/core/testing/src/test_bed.ts:227:36)
      at Object.<anonymous> (src/lib/my-lib.service.spec.ts:19:23)

  ● MyLibService › should be created

    expect(received).toBeTruthy()

    Received: undefined

      21 | 
      22 |   it('should be created', () => {
    > 23 |     expect(service).toBeTruthy();
         |                     ^
      24 |   });
      25 | });
      26 | 

      at Object.<anonymous> (src/lib/my-lib.service.spec.ts:23:21)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.182 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-lib-with-jest@0.0.0 test:lib: `jest --config ./projects/my-lib/jest.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-lib-with-jest@0.0.0 test:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/canserkanuren/.npm/_logs/2020-11-02T09_15_59_501Z-debug.log
```

Even though I tried to compile Angular sources with ngcc, I still get the same error as above...
## To Reproduce

- Init a new Angular library project
- Add Jest basic configuration
- Add `@angular/material` and add a random module exported by Angular Material, by instance, `MatSnackBarModule`
- Run unit tests with Jest
- Unit tests fail

## Link to repo (highly encouraged)

I have made two projects, one with Angular's basic configuration, e.g. Karma, and the other one with Jest.
Karma project : https://github.com/canserkanuren/karma-unit-test-material
Jest project : https://github.com/canserkanuren/jest-unit-test-material

In the Jest project, you can find two branches : 
- `master`, using current released version of `jest-preset-angular` : 8.3.2
- `9.0.0`: using next version of `jest-preset-angular`: 9.0.0.next-1

## Error log:

```
# content of error stacktrace :

```

## envinfo

```
System:
    OS: Mac

Npm packages:
    jest: 26.6.1
    jest-preset-angular: 8.3.2 / 9.0.0.next-1
    typescript: 4.0.2
```

**Comment by ahnpnl** [comment] 2020-11-02 09:25
Did you run ngcc already ?

**Comment by canserkanuren** [comment] 2020-11-02 09:30
Yes, I just did it, and a new error appeared : 

```
> my-lib-with-jest@0.0.0 test:lib /Users/canserkanuren/workspace/angular-material-lib/my-lib-with-jest
> jest --config ./projects/my-lib/jest.config.js

 FAIL  projects/my-lib/src/lib/my-lib.service.spec.ts
  MyLibService
    ✕ should be created (302 ms)

  ● MyLibService › should be created

    In this configuration Angular requires Zone.js

      at new NgZone (../../../packages/core/src/zone/ng_zone.ts:124:13)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.compileTestModule (../../../packages/core/testing/src/r3_test_bed_compiler.ts:659:20)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.finalize (../../../packages/core/testing/src/r3_test_bed_compiler.ts:245:10)
      at TestBedRender3.get (../../../packages/core/testing/src/r3_test_bed.ts:379:43)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../../../packages/core/testing/src/r3_test_bed.ts:278:25)
      at Function.Object.<anonymous>.TestBedRender3.inject (../../../packages/core/testing/src/r3_test_bed.ts:167:33)
      at Object.<anonymous> (src/lib/my-lib.service.spec.ts:19:23)

  ● MyLibService › should be created

    expect(received).toBeTruthy()

    Received: undefined

      21 | 
      22 |   it('should be created', () => {
    > 23 |     expect(service).toBeTruthy();
         |                     ^
      24 |   });
      25 | });
      26 | 

      at Object.<anonymous> (src/lib/my-lib.service.spec.ts:23:21)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.069 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-lib-with-jest@0.0.0 test:lib: `jest --config ./projects/my-lib/jest.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-lib-with-jest@0.0.0 test:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/canserkanuren/.npm/_logs/2020-11-02T09_27_44_674Z-debug.log
```

Am I doing something wrong ? I ran ngcc through `npx ngcc`...

Thank you for you help!

**Comment by ahnpnl** [comment] 2020-11-02 09:33
Did you add `import 'jest-preset-angular/setup-jest' in your jest setup ?

**Comment by canserkanuren** [comment] 2020-11-02 09:36
Just did it, and I have another error :
```
> my-lib-with-jest@0.0.0 test:lib /Users/canserkanuren/workspace/angular-material-lib/my-lib-with-jest
> jest --config ./projects/my-lib/jest.config.js

 FAIL  projects/my-lib/src/lib/my-lib.service.spec.ts
  MyLibService
    ✕ should be created (296 ms)

  ● MyLibService › should be created

    This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
    This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

    Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.

      at ɵɵinvalidFactoryDep (../../../packages/core/src/di/injector_compatibility.ts:155:9)
      at Object.MyLibService_Factory [as factory] (../../ng:/MyLibService/ɵfac.js:3:40)
      at R3Injector.Object.<anonymous>.R3Injector.hydrate (../../../packages/core/src/di/r3_injector.ts:411:29)
      at R3Injector.Object.<anonymous>.R3Injector.get (../../../packages/core/src/di/r3_injector.ts:208:23)
      at NgModuleRef$1.Object.<anonymous>.NgModuleRef$1.get (../../../packages/core/src/render3/ng_module_ref.ts:80:29)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../../../packages/core/testing/src/r3_test_bed.ts:278:48)
      at Function.Object.<anonymous>.TestBedRender3.inject (../../../packages/core/testing/src/r3_test_bed.ts:167:33)
      at src/lib/my-lib.service.spec.ts:19:23

  ● MyLibService › should be created

    expect(received).toBeTruthy()

    Received: undefined

      21 | 
      22 |   it('should be created', () => {
    > 23 |     expect(service).toBeTruthy();
         |                     ^
      24 |   });
      25 | });
      26 | 

      at src/lib/my-lib.service.spec.ts:23:21

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.362 s, estimated 4 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-lib-with-jest@0.0.0 test:lib: `jest --config ./projects/my-lib/jest.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-lib-with-jest@0.0.0 test:lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/canserkanuren/.npm/_logs/2020-11-02T09_35_38_029Z-debug.log
```

**Comment by canserkanuren** [comment] 2020-11-02 09:40
After trying multiples times, it seems to be working correctly.
Thank you for your time.

**Comment by ahnpnl** [comment] 2020-11-02 09:46
The error you got is expected, I ran into it too. The workaround is adjust your `tsconfig.spec.json` in your lib to
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/spec",
    "types": ["jest", "node"]
  },
  "files": ["src/test.ts"],
  "include": ["**/*.ts", "**/*.d.ts"]
}
```

We are still working on #562 so your effort to test our `next` version is very appreciated. I would like to keep this issue open to continue the work in #562

**Comment by canserkanuren** [comment] 2020-11-02 09:49
I can't find a difference between the `tsconfig.spec.json` you wrote above and mine..

**Comment by ahnpnl** [comment] 2020-11-02 10:14
the only difference is `"include": ["**/*.ts", "**/*.d.ts"]`. When generating a library via Angular CLI, the `tsconfig.spec.json` in the library will be `"include": ["**/*.spec.ts", "**/*.d.ts"]`.

It's a bug with **v9.0.0-next.1** that it doesn't work with initially generated `tsconfig.spec.json`.

**Comment by canserkanuren** [comment] 2020-11-02 10:34
Oh yeah, sorry didn't see that. Thank you for your time!

**Comment by wtho** [comment] 2020-11-02 11:09
@canserkanuren is this resolved? If so, please close the issue.
Thanks!

**Comment by canserkanuren** [comment] 2020-11-02 11:13
Hi, yes it is resolved, but @ahnpnl said that he wanted to keep this issue open, so I didn't close it.
Should I keep it open ?
Thanks!

**Comment by ahnpnl** [comment] 2020-11-02 11:16
@wtho I intended to keep this issue open because it needs to be fixed. The problem is resolved now via a workaround

**Comment by wtho** [comment] 2020-11-02 11:56
Ok cool!
Sorry, I overlooked that comment 🙌

**Comment by ahnpnl** [comment] 2020-11-03 13:28
I will close this issue. I can no longer reproduce the DI error with my company projects. With a newly generated project from Angular CLI, **v9.0.0-next.1** works well.

**Closed by ahnpnl** 2020-11-03 13:28 UTC
Labels: Not An Issue
