### ISSUE TITLE
when a run my code, i face these errors. after applying all possible solutions (npm install),(npm install @angular/core) these errors do not resolve. kindly help me out

### ISSUE THREAD

**Issue by Murkhassan86** [thymikee/jest-preset-angular#402] opened 2020-06-30 10:36 UTC
![Capture](https://user-images.githubusercontent.com/67417764/86116634-9fef5b00-ba82-11ea-833c-a23e11daa90e.PNG)
# No Template

👉 Please follow one of the issue templates provided by the repo - if you are seeing this message, it means you haven't.

If you don't follow the issue template, we may immediately close it.

**Comment by ahnpnl** [comment] 2020-06-30 10:42
would you please provide your repo ?

**Comment by wtho** [comment] 2020-07-09 14:32
I will close this issue for now due to lacking issue information. If you provide more information or a reproduction we can reopen it again.

**Closed by wtho** 2020-07-09 14:32 UTC
