### ISSUE TITLE
[Bug]: SyntaxError: The requested module './config' does not provide an export named 'Config' / DownlevelTransform does not work correctly

### ISSUE THREAD

**Issue by CSchulz** [thymikee/jest-preset-angular#2165] opened 2023-09-19 11:15 UTC
### Version

13.1.1

### Steps to reproduce

1. Checkout repository https://github.com/CSchulz/jest-preset-angular with branch esm-interface (https://github.com/CSchulz/jest-preset-angular/tree/esm-interface)
2. Switch to examples/example-app-v15
3. Run npm i
4. Run `npm run test-esm --  src/app/test.service.spec.ts` -> See error in src/app/test.service.spec.ts
6. Run `npm run test --  src/app/test.service.spec.ts` -> No error
7. Run `npm run test-esm-ts-jest --  src/app/test.service.spec.ts` -> No error

### Expected behavior

ESM variant should work like CJS variant.

### Actual behavior

Module instantiation fails

    SyntaxError: The requested module './config' does not provide an export named 'Config'
      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:699:5)

It breaks during the internal module handling of Node in the last line:

```
  async link(linker) {
    if (this[kWrap] === undefined) {
      throw new ERR_VM_MODULE_NOT_MODULE();
    }
    validateFunction(linker, 'linker');
    if (this.status === 'linked') {
      throw new ERR_VM_MODULE_ALREADY_LINKED();
    }
    if (this.status !== 'unlinked') {
      throw new ERR_VM_MODULE_STATUS('must be unlinked');
    }
    await this[kLink](linker);
    this[kWrap].instantiate();
  }
```

This is the call stack:

```
Error: 
    at eval (eval at link (node:internal/vm/module:200:17), <anonymous>:1:7)
    at SourceTextModule.link (node:internal/vm/module:200:17)
    at Runtime.linkAndEvaluateModule (examples\example-app-v15\node_modules\jest-runtime\build\index.js:699:5)
    at jestAdapter (examples\example-app-v15\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:75:5)
    at runTestInternal (examples\example-app-v15\node_modules\jest-runner\build\runTest.js:367:16)
    at runTest (examples\example-app-v15\node_modules\jest-runner\build\runTest.js:444:34)
```

![image](https://github.com/kulshekhar/ts-jest/assets/1520593/5cf3652b-5ded-4531-838f-3d8781321050)

### Additional context

https://github.com/yargs/yargs/issues/2068
https://github.com/jestjs/jest/issues/12284 respective https://github.com/jestjs/jest/issues/12574
https://github.com/kulshekhar/ts-jest/issues/4167

There is an existing workaround to include all source files in the tsconfig.json for the spec files (see tsconfig.spec.json).
This workaround seems only to work within the module itself til you have package boundaries mapped by the module name mapper.

I have also reported it at the jest repo, https://github.com/jestjs/jest/issues/14395

By creating a reproduction example I have found out that the issue is within the `constructorParametersDownlevelTransform`.
If you remove this transformer from the list everything works like expected.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by CSchulz** [comment] 2023-09-19 20:28
I have also added an angular 16 example with the same issue.

I wasn't able to understand why we need the downlevel transformer, is there any further documentation about it?
Furthermore is it still required if we are using ESM?

**Comment by ahnpnl** [comment] 2023-09-20 11:51
You can check https://github.com/angular/angular-cli/pull/14473 for the explanation of the transformer.

Hopefully when Angular goes fully standalone component, at some points they will drop the need of that transformer. For now, without it, DI won’t work. Angular relies a lot on typescript compiler API to do some magic with codes. 

It’s not possible to fix this problems in this repo. Hopefully Angular CLI team experimental work will solve it someday.

**Comment by CSchulz** [comment] 2023-09-20 21:45
Does that basically means there will be a lot of different use cases where jest esm is not applicable for angular?

**Comment by ahnpnl** [comment] 2023-09-20 22:25
This problem already existed with CJS mode too, not only to ESM. The issue is about transforming codes with incomplete information of TypeScript compiler which is used via `ts-jest`, see related issue #963 

We tried to mimic the behavior of Angular CLI for Jest, but it's not exactly the same due to limitation of Jest transforming process. The ideal way is that, all the codes of Angular need to be transpiled before Jest kicks in.

**Comment by CSchulz** [comment] 2023-09-21 16:15
I have noticed following to have a workaround for the issue:

- Wrapping the injected interface into an injection token
- Include everything in the typescript program via tsconfig-esm.spec.json

In my honest opinion it looks like the imports which are generated are not resolvable by ESM, because the interfaces are already gone during the typescript transform process and adding them to the program prevents that behavior?
I didn't managed it yet to retrieve and compare the transformed output passed to jest. Hopefully I will find there another hint.

**Comment by ahnpnl** [comment] 2024-05-10 03:58
Good news now that this issue can be completely solved with `inject` function. Indeed the downlevel constructor transformer needs lots of information from TypeScript Program.

Acknowledging this caveat, I will close this issue.

**Closed by ahnpnl** 2024-05-10 03:58 UTC
Labels: Bug Report, Needs Triage
