### ISSUE TITLE
Service injection resolution error in Jest Tests with `{providedIn: 'root'}` (Angular v7)

### ISSUE THREAD

**Issue by susilpadhi** [thymikee/jest-preset-angular#348] opened 2020-02-16 16:02 UTC
### Error:
`Uncaught Error: Can't resolve all parameters for EventsListComponent: (?).
    at syntaxError (compiler.js:2193)`

##### Component 
```ts
import { Component, OnInit } from '@angular/core';
import { EventService } from './Shared/event.service';

@Component({
    selector: 'app-events-list',
    template: `
    <p>
     {{newcomponent}}
    </p>
    <p>
      Today's Date : {{todaydate}}
    </p>
    `
  })
  export class EventsListComponent implements OnInit {
    public todaydate;
    newcomponent = 'Entered in new component created';
    constructor(private myservice: EventService) {}
    ngOnInit() {
       this.todaydate = this.myservice.showTodayDate();
    }
  }
```
##### Service
```ts
import { Injectable } from '@angular/core';
@Injectable({
  providedIn: 'root'
})
export class EventService {
  constructor() { }
  showTodayDate() {
     const ndate = new Date();
     return ndate;
  }
}
`

**Comment by wtho** [comment] 2020-02-16 17:15
Hey!
Thanks for reporting, but to help you we need some more information about your setup.
* Which Angular version are you using (v7 according to your title)
* What `jest-preset-angular` version?
* What does your jest config look like?
* Also I would like to see your `tsconfig.spec.json`
* What does the failing test look like?
* Can you check if this is related to #288? Although if you do use Angular v7, this should not be the same issue.

If you are very eager to have this solved, a minimal example hosted on GitHub would be tremendous.
Cheers!

**Comment by susilpadhi** [comment] 2020-02-17 03:47
I don't have any "jest-preset-angular", in my code base.

**Comment by ahnpnl** [comment] 2020-02-17 03:51
Would you please provide a minimum reproducible repo for your problem ?

**Comment by wtho** [comment] 2020-02-17 10:19
This is the repository of `jest-preset-angular`, if you want to use Jest with Angular, you should use this preset as described in the README.

If you are not interested in testing with Jest, you are probably at the wrong place and you should head over to stackoverflow for help.
Cheers!

**Comment by wtho** [comment] 2020-03-12 20:57
@susilpadhi if you do not have any objections, I would like to close this issue, as it seems to be unrelated to `jest-preset-angular`.

**Closed** 2021-01-06 10:44 UTC
Labels: :man_shrugging: Needs More Info
