### ISSUE TITLE
Handle compiled libraries out of the box

### ISSUE THREAD

**Issue by ajkettun** [thymikee/jest-preset-angular#365] opened 2020-03-27 05:38 UTC
Preset configuration doesn't seem to work with component libraries. We have a completely separate Angular workspace for our component library which is a standard ng generated component library built with ngcc to dist.

Project which uses the component library is configured to consume it directly from dist (we do not publish the library nor install it to node_modules). Project and library components work fine and Karma tests work fine too but Jest fails if test uses any component from component library with templateUrl or styleUrls: Error: connect ECONNREFUSED 127.0.0.1:80.

We haven overidden globals so the preset astTransformers are in place and components in the project which have templateUrl or styleUrls work fine with Jest.

**Comment by ahnpnl** [comment] 2020-03-27 09:06
hi, would you please share your minimum repo with us so we can reproduce the issue ?

**Comment by ajkettun** [comment] 2020-03-28 08:56
Thanks for the quick reply. Here:

https://github.com/ajkettun/jest-repro

**Comment by ajkettun** [comment] 2020-03-30 09:31
Problem can be circumvented by using public-api.ts directly. But shouldn't it work against the compiled library too?
```
    "moduleNameMapper": {
      "^repro-lib": "<rootDir>/../jest-repro/projects/repro-lib/src/public-api.ts"
    }
```

**Comment by wtho** [comment] 2020-03-31 14:55
If you run `ng build --prod` in `jest-repro` for `repro-lib`, it also works.

**Comment by ahnpnl** [comment] 2020-04-06 19:52
I’m curious if nrwl nx faces the same issue. This type of repo can be seen usually in monorepo type

**Comment by fabioformosa** [comment] 2020-05-12 09:32
> We haven overidden globals so the preset astTransformers are in place and components in the project which have templateUrl or styleUrls work fine with Jest.

@ajkettun Hi, could you report a snippet with your workaround about astTransformers? thank you

**Comment by ahnpnl** [comment] 2020-07-09 15:02
> Problem can be circumvented by using public-api.ts directly. But shouldn't it work against the compiled library too?
> 
> ```
>     "moduleNameMapper": {
>       "^repro-lib": "<rootDir>/../jest-repro/projects/repro-lib/src/public-api.ts"
>     }
> ```

Indeed the preset configuration doesn't take care of this situation, but this change is correct and valid as `jest` module resolver needs information where to look for the library. 

Moreover, if pointing to `dist` folder, that won't work for now because the preset is lack of some possibilities to handle compiled libraries which is related to how Angular compiler logic (see #406 for more information).

@fabioformosa you can follow the approach of setting `moduleNameMapper`.

**Comment by ahnpnl** [comment] 2020-07-10 11:33
> Problem can be circumvented by using public-api.ts directly. But shouldn't it work against the compiled library too?
> 
> ```
>     "moduleNameMapper": {
>       "^repro-lib": "<rootDir>/../jest-repro/projects/repro-lib/src/public-api.ts"
>     }
> ```

Hi @ajkettun

What you can do to make this work is:

- Build the `repro-lib` library with `ng build repro-lib --prod`

- Configure your `moduleNameMapper` to
```
"moduleNameMapper": {
      "^@angular/(.*)$": "<rootDir>/node_modules/@angular/$1",
      "^repro-lib": "<rootDir>/../jest-repro/dist/repro-lib/bundles/repro-lib.umd.js"
    },
```

At the moment, `jest-preset-angular` is working on support ivy libraries, you can follow the progress in #389 . So you can only run `jest` with VE libraries for now.

@fabioformosa you should configure your `moduleNameMapper` to make it work.

I will close this issue as it is only about configuration.

**Closed by ahnpnl** 2020-07-10 11:33 UTC
Labels: :rocket:Feature Request
