### ISSUE TITLE
[Bug]: Tests fail with `ReferenceError: document is not defined` on Angular 19

### ISSUE THREAD

**Issue by marcelhohn** [thymikee/jest-preset-angular#2883] opened 2024-11-29 11:23 UTC
### Version

14.4.1

### Steps to reproduce

1. Create a new Angular 19 project via the Angular CLI
2. Uninstall Jasmine/Karma dependencies and follow [instructions](https://thymikee.github.io/jest-preset-angular/docs/getting-started/installation/) to use Jest for testing
3. Install `ts-node` to use a TS file for Jest config
4. Run `npm run test` 

### Expected behavior

The tests pass

### Actual behavior

The tests fail, with the following error:

```
  ● AppComponent › should render title

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: document is not defined

```

### Additional context

A reproduction example is [here](https://github.com/marcelhohn/angular-playground/tree/angular-v19-jest). Note that I created it by upgrading from Angular v18 to v19, but the setup and bug remain the same as in a newly created Angular v19 app.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics     
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\Programs\nodejs\node.EXE
    npm: 10.2.4 - ~\AppData\Local\Programs\nodejs\npm.CMD
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by dm-gc** [comment] 2024-11-29 12:44
I also have this issue on Angular 17 (it has been driving me crazy for the past four hours or so)!

**Angular version**: 17.3.3
**jest**: 29.7.0
**jest-preset-angular**: 14.4.1

```
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
Consider using the "jsdom" test environment.

ReferenceError: document is not defined

  at node_modules/nwsapi/src/nwsapi.js:215:21
  at Factory (node_modules/nwsapi/src/nwsapi.js:245:6)
  at initNwsapi (node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:10:10)
  at exports.addNwsapi (node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:38:24)
```

**setup-jest.ts:**
```
import { setupZoneTestEnv } from 'jest-preset-angular/setup-env/zone';

setupZoneTestEnv();
```

**jest.config.ts:**
```
import type { Config } from 'jest';

const jestConfig: Config = {
    preset: 'jest-preset-angular',
    setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],

};

export default jestConfig;
```

**Also fails with following jest.config.ts:**
```
import presets from 'jest-preset-angular/presets';
import type { Config } from 'jest';

const presetConfig = presets.createCjsPreset({
  //...options
});

const jestConfig: Config = {
  ...presetConfig,
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
};

export default jestConfig;
```

**tsconfig.spec.json**:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": [
      "jest"
    ],
  },
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}

```

**Comment by tomastrajan** [comment] 2024-11-29 12:53
Same problem

**Comment by dm-gc** [comment] 2024-11-29 12:58
Guys and gals,

as indicated by error stack it is probably caused by latest version (2.2.14) of **nwsapi**:

![bild](https://github.com/user-attachments/assets/5b5fae8d-7753-4df1-95cd-860ab54705cd)

See open issue at their repo: https://github.com/dperini/nwsapi/issues/135

**Comment by tomastrajan** [comment] 2024-11-29 13:08
Thank you so much, I was losing my mind😅

Is this somehting which will be fixed in the next release of `jest-preset-angular` ?

**Comment by tomastrajan** [comment] 2024-11-29 13:44
@dm-gc right, yeah it's unfortunate.

Hmm, I was more thinking in a direction that the `jest-preset-angular` would fix the version of it's own transitive dep, the `nwsapi`
so such thing could be prevented because it would need to be upgraded manually by the `jest-preset-angular` maintainers in the future?

but actually it's even worse lol

![image](https://github.com/user-attachments/assets/1ef83126-8327-4b91-8684-91ff9fc12a40)


so it's fully on the jest side 🤦

**Closed** 2024-12-20 09:52 UTC
Labels: Upstream Bug

**Comment by ahnpnl** [comment] 2025-01-10 13:10
Update doc at https://thymikee.github.io/jest-preset-angular/docs/guides/jsdom-version can help with this issue. Please check out and let us know if it helps 😃
