### ISSUE TITLE
Unable to execute Jest esm tests with amcharts5 lib

### ISSUE THREAD

**Issue by tidou44** [thymikee/jest-preset-angular#2059] opened 2023-05-04 07:21 UTC
Hello everyone
I'm trying to migrate the execution of Jest unit tests in ESM isolated mode.
Execution goes well (and much faster than in normal mode), but using the @amcharts/amcharts graph library execution fails.

```
FAIL  src/app/app.component.router.spec.ts
  ● Test suite failed to run

    Must use import to load ES Module: /vif/tmp/jest-preset-angular-main/examples/example-app-v15/node_modules/d3-shape/src/index.js

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:841:21)
```

I tried to add transformIgnorePattern in jest config file but it's the same.

```
 transformIgnorePatterns: [`/node_modules/(?!d3-|@amcharts|tslib)`]
```
Does anyone knows what is wrong ?

Thank you in advance

**Comment by ahnpnl** [comment] 2023-05-04 07:37
Would you please use https://github.com/thymikee/jest-preset-angular/tree/main/examples to make a reproduce example?

**Comment by ahnpnl** [comment] 2024-05-10 03:31
This error is not able to reproduce anymore with the latest version of `example-app-v15` and `jest-preset-angular`. I'll close this issue. If you still encounter it, pls update your reproduce steps.

**Closed by ahnpnl** 2024-05-10 03:31 UTC
